export const heads = [
	{
		name: "DR. G. DEVASENA",
		role: "Training and Placement Officer",
		imageUrl: "/teams/devasena.jpg",
		email: "placement@iiitt.ac.in",
		phone: "9042473621",
		linkedinId: "tnp-cell-iiit-tiruchirappalli",
	},
	{
		name: "DR. D. SURESH",
		role: "Additional Incharge",
		imageUrl: "/teams/Suresh.jpeg",
		email: "sureshd@iiitt.ac.in",
		phone: "8827958387",
		linkedinId: "tnp-cell-iiit-tiruchirappalli",
	},
];

export const representatives = [
	{
		name: "AKASH YADAV",
		role: "TnP Representatives",
		imageUrl: "/teams/akash_yadav.jpg",
		email: "211205@iiitt.ac.in",
		phone: "9306854791, 9518243295",
		linkedinId: "akash-yadav-23897b228",
	},
	{
		name: "AYUSH KUMAR",
		role: "Site Designer & Maintainer, TnP Rep",
		imageUrl: "/teams/ayush_kumar.jpeg",
		email: "211107@iiitt.ac.in",
		phone: "7061357391",
		linkedinId: "rtnayush",
		// githubUrl: "",
	},
	{
		name: "ATHARVA SANJAY MORE",
		role: "TnP Representatives",
		imageUrl: "/teams/atharva_more.jpg",
		email: "211105@iiitt.ac.in",
		phone: "9324373587",
		linkedinId: "atharvamor3",
		// githubUrl: "",
	},
	{
		name: "G. CHARAN",
		role: "TnP Representatives",
		imageUrl: "/teams/g_charan.jpg",
		email: "211210@iiitt.ac.in",
		phone: "6301745974",
		linkedinId: "charan-galanki-161612253",
		// githubUrl: "",
	},
	{
		name: "Sayan Das",
		role: "TnP Representatives",
		imageUrl: "/teams/sanyan_das.jpg",
		email: "232103@iiitt.ac.in",
		phone: "9612547652",
		linkedinId: "sayan-das-631751217",
		// githubUrl: "",
	},
];
